/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QuickStartRouteImport } from './routes/quick-start'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as SkillsRouteRouteImport } from './routes/skills/route'
import { Route as OpsRouteRouteImport } from './routes/ops/route'
import { Route as KnowledgeRouteRouteImport } from './routes/knowledge/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SkillsIndexRouteImport } from './routes/skills/index'
import { Route as OpsIndexRouteImport } from './routes/ops/index'
import { Route as KnowledgeIndexRouteImport } from './routes/knowledge/index'
import { Route as SkillsSlugRouteImport } from './routes/skills/$slug'
import { Route as OpsLoginRouteImport } from './routes/ops/login'
import { Route as KnowledgeIdRouteImport } from './routes/knowledge/$id'
import { Route as DotwellKnownOauthProtectedResourceRouteImport } from './routes/[.]well-known.oauth-protected-resource'
import { Route as DotwellKnownOauthAuthorizationServerRouteImport } from './routes/[.]well-known.oauth-authorization-server'
import { Route as OpsMatrixIndexRouteImport } from './routes/ops/matrix/index'
import { Route as OpsKnowledgeIndexRouteImport } from './routes/ops/knowledge/index'
import { Route as DotwellKnownOauthProtectedResourceSplatRouteImport } from './routes/[.]well-known.oauth-protected-resource.$'
import { Route as ApiOpsAuthLogoutRouteImport } from './routes/api/ops/auth/logout'
import { Route as ApiOpsAuthLoginRouteImport } from './routes/api/ops/auth/login'
import { Route as ApiOpsAuthCallbackRouteImport } from './routes/api/ops/auth/callback'

const QuickStartRoute = QuickStartRouteImport.update({
  id: '/quick-start',
  path: '/quick-start',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRouteRoute = SkillsRouteRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsRouteRoute = OpsRouteRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRouteRoute = KnowledgeRouteRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsIndexRoute = SkillsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SkillsRouteRoute,
} as any)
const OpsIndexRoute = OpsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OpsRouteRoute,
} as any)
const KnowledgeIndexRoute = KnowledgeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KnowledgeRouteRoute,
} as any)
const SkillsSlugRoute = SkillsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SkillsRouteRoute,
} as any)
const OpsLoginRoute = OpsLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => OpsRouteRoute,
} as any)
const KnowledgeIdRoute = KnowledgeIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => KnowledgeRouteRoute,
} as any)
const DotwellKnownOauthProtectedResourceRoute =
  DotwellKnownOauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownOauthAuthorizationServerRoute =
  DotwellKnownOauthAuthorizationServerRouteImport.update({
    id: '/.well-known/oauth-authorization-server',
    path: '/.well-known/oauth-authorization-server',
    getParentRoute: () => rootRouteImport,
  } as any)
const OpsMatrixIndexRoute = OpsMatrixIndexRouteImport.update({
  id: '/matrix/',
  path: '/matrix/',
  getParentRoute: () => OpsRouteRoute,
} as any)
const OpsKnowledgeIndexRoute = OpsKnowledgeIndexRouteImport.update({
  id: '/knowledge/',
  path: '/knowledge/',
  getParentRoute: () => OpsRouteRoute,
} as any)
const DotwellKnownOauthProtectedResourceSplatRoute =
  DotwellKnownOauthProtectedResourceSplatRouteImport.update({
    id: '/$',
    path: '/$',
    getParentRoute: () => DotwellKnownOauthProtectedResourceRoute,
  } as any)
const ApiOpsAuthLogoutRoute = ApiOpsAuthLogoutRouteImport.update({
  id: '/api/ops/auth/logout',
  path: '/api/ops/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpsAuthLoginRoute = ApiOpsAuthLoginRouteImport.update({
  id: '/api/ops/auth/login',
  path: '/api/ops/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpsAuthCallbackRoute = ApiOpsAuthCallbackRouteImport.update({
  id: '/api/ops/auth/callback',
  path: '/api/ops/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/knowledge': typeof KnowledgeRouteRouteWithChildren
  '/ops': typeof OpsRouteRouteWithChildren
  '/skills': typeof SkillsRouteRouteWithChildren
  '/mcp': typeof McpRoute
  '/quick-start': typeof QuickStartRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/.well-known/oauth-protected-resource': typeof DotwellKnownOauthProtectedResourceRouteWithChildren
  '/knowledge/$id': typeof KnowledgeIdRoute
  '/ops/login': typeof OpsLoginRoute
  '/skills/$slug': typeof SkillsSlugRoute
  '/knowledge/': typeof KnowledgeIndexRoute
  '/ops/': typeof OpsIndexRoute
  '/skills/': typeof SkillsIndexRoute
  '/.well-known/oauth-protected-resource/$': typeof DotwellKnownOauthProtectedResourceSplatRoute
  '/ops/knowledge/': typeof OpsKnowledgeIndexRoute
  '/ops/matrix/': typeof OpsMatrixIndexRoute
  '/api/ops/auth/callback': typeof ApiOpsAuthCallbackRoute
  '/api/ops/auth/login': typeof ApiOpsAuthLoginRoute
  '/api/ops/auth/logout': typeof ApiOpsAuthLogoutRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/quick-start': typeof QuickStartRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/.well-known/oauth-protected-resource': typeof DotwellKnownOauthProtectedResourceRouteWithChildren
  '/knowledge/$id': typeof KnowledgeIdRoute
  '/ops/login': typeof OpsLoginRoute
  '/skills/$slug': typeof SkillsSlugRoute
  '/knowledge': typeof KnowledgeIndexRoute
  '/ops': typeof OpsIndexRoute
  '/skills': typeof SkillsIndexRoute
  '/.well-known/oauth-protected-resource/$': typeof DotwellKnownOauthProtectedResourceSplatRoute
  '/ops/knowledge': typeof OpsKnowledgeIndexRoute
  '/ops/matrix': typeof OpsMatrixIndexRoute
  '/api/ops/auth/callback': typeof ApiOpsAuthCallbackRoute
  '/api/ops/auth/login': typeof ApiOpsAuthLoginRoute
  '/api/ops/auth/logout': typeof ApiOpsAuthLogoutRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/knowledge': typeof KnowledgeRouteRouteWithChildren
  '/ops': typeof OpsRouteRouteWithChildren
  '/skills': typeof SkillsRouteRouteWithChildren
  '/mcp': typeof McpRoute
  '/quick-start': typeof QuickStartRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/.well-known/oauth-protected-resource': typeof DotwellKnownOauthProtectedResourceRouteWithChildren
  '/knowledge/$id': typeof KnowledgeIdRoute
  '/ops/login': typeof OpsLoginRoute
  '/skills/$slug': typeof SkillsSlugRoute
  '/knowledge/': typeof KnowledgeIndexRoute
  '/ops/': typeof OpsIndexRoute
  '/skills/': typeof SkillsIndexRoute
  '/.well-known/oauth-protected-resource/$': typeof DotwellKnownOauthProtectedResourceSplatRoute
  '/ops/knowledge/': typeof OpsKnowledgeIndexRoute
  '/ops/matrix/': typeof OpsMatrixIndexRoute
  '/api/ops/auth/callback': typeof ApiOpsAuthCallbackRoute
  '/api/ops/auth/login': typeof ApiOpsAuthLoginRoute
  '/api/ops/auth/logout': typeof ApiOpsAuthLogoutRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/knowledge'
    | '/ops'
    | '/skills'
    | '/mcp'
    | '/quick-start'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/oauth-protected-resource'
    | '/knowledge/$id'
    | '/ops/login'
    | '/skills/$slug'
    | '/knowledge/'
    | '/ops/'
    | '/skills/'
    | '/.well-known/oauth-protected-resource/$'
    | '/ops/knowledge/'
    | '/ops/matrix/'
    | '/api/ops/auth/callback'
    | '/api/ops/auth/login'
    | '/api/ops/auth/logout'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mcp'
    | '/quick-start'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/oauth-protected-resource'
    | '/knowledge/$id'
    | '/ops/login'
    | '/skills/$slug'
    | '/knowledge'
    | '/ops'
    | '/skills'
    | '/.well-known/oauth-protected-resource/$'
    | '/ops/knowledge'
    | '/ops/matrix'
    | '/api/ops/auth/callback'
    | '/api/ops/auth/login'
    | '/api/ops/auth/logout'
  id:
    | '__root__'
    | '/'
    | '/knowledge'
    | '/ops'
    | '/skills'
    | '/mcp'
    | '/quick-start'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/oauth-protected-resource'
    | '/knowledge/$id'
    | '/ops/login'
    | '/skills/$slug'
    | '/knowledge/'
    | '/ops/'
    | '/skills/'
    | '/.well-known/oauth-protected-resource/$'
    | '/ops/knowledge/'
    | '/ops/matrix/'
    | '/api/ops/auth/callback'
    | '/api/ops/auth/login'
    | '/api/ops/auth/logout'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KnowledgeRouteRoute: typeof KnowledgeRouteRouteWithChildren
  OpsRouteRoute: typeof OpsRouteRouteWithChildren
  SkillsRouteRoute: typeof SkillsRouteRouteWithChildren
  McpRoute: typeof McpRoute
  QuickStartRoute: typeof QuickStartRoute
  DotwellKnownOauthAuthorizationServerRoute: typeof DotwellKnownOauthAuthorizationServerRoute
  DotwellKnownOauthProtectedResourceRoute: typeof DotwellKnownOauthProtectedResourceRouteWithChildren
  ApiOpsAuthCallbackRoute: typeof ApiOpsAuthCallbackRoute
  ApiOpsAuthLoginRoute: typeof ApiOpsAuthLoginRoute
  ApiOpsAuthLogoutRoute: typeof ApiOpsAuthLogoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/quick-start': {
      id: '/quick-start'
      path: '/quick-start'
      fullPath: '/quick-start'
      preLoaderRoute: typeof QuickStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops': {
      id: '/ops'
      path: '/ops'
      fullPath: '/ops'
      preLoaderRoute: typeof OpsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/': {
      id: '/skills/'
      path: '/'
      fullPath: '/skills/'
      preLoaderRoute: typeof SkillsIndexRouteImport
      parentRoute: typeof SkillsRouteRoute
    }
    '/ops/': {
      id: '/ops/'
      path: '/'
      fullPath: '/ops/'
      preLoaderRoute: typeof OpsIndexRouteImport
      parentRoute: typeof OpsRouteRoute
    }
    '/knowledge/': {
      id: '/knowledge/'
      path: '/'
      fullPath: '/knowledge/'
      preLoaderRoute: typeof KnowledgeIndexRouteImport
      parentRoute: typeof KnowledgeRouteRoute
    }
    '/skills/$slug': {
      id: '/skills/$slug'
      path: '/$slug'
      fullPath: '/skills/$slug'
      preLoaderRoute: typeof SkillsSlugRouteImport
      parentRoute: typeof SkillsRouteRoute
    }
    '/ops/login': {
      id: '/ops/login'
      path: '/login'
      fullPath: '/ops/login'
      preLoaderRoute: typeof OpsLoginRouteImport
      parentRoute: typeof OpsRouteRoute
    }
    '/knowledge/$id': {
      id: '/knowledge/$id'
      path: '/$id'
      fullPath: '/knowledge/$id'
      preLoaderRoute: typeof KnowledgeIdRouteImport
      parentRoute: typeof KnowledgeRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof DotwellKnownOauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-authorization-server': {
      id: '/.well-known/oauth-authorization-server'
      path: '/.well-known/oauth-authorization-server'
      fullPath: '/.well-known/oauth-authorization-server'
      preLoaderRoute: typeof DotwellKnownOauthAuthorizationServerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops/matrix/': {
      id: '/ops/matrix/'
      path: '/matrix'
      fullPath: '/ops/matrix/'
      preLoaderRoute: typeof OpsMatrixIndexRouteImport
      parentRoute: typeof OpsRouteRoute
    }
    '/ops/knowledge/': {
      id: '/ops/knowledge/'
      path: '/knowledge'
      fullPath: '/ops/knowledge/'
      preLoaderRoute: typeof OpsKnowledgeIndexRouteImport
      parentRoute: typeof OpsRouteRoute
    }
    '/.well-known/oauth-protected-resource/$': {
      id: '/.well-known/oauth-protected-resource/$'
      path: '/$'
      fullPath: '/.well-known/oauth-protected-resource/$'
      preLoaderRoute: typeof DotwellKnownOauthProtectedResourceSplatRouteImport
      parentRoute: typeof DotwellKnownOauthProtectedResourceRoute
    }
    '/api/ops/auth/logout': {
      id: '/api/ops/auth/logout'
      path: '/api/ops/auth/logout'
      fullPath: '/api/ops/auth/logout'
      preLoaderRoute: typeof ApiOpsAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ops/auth/login': {
      id: '/api/ops/auth/login'
      path: '/api/ops/auth/login'
      fullPath: '/api/ops/auth/login'
      preLoaderRoute: typeof ApiOpsAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ops/auth/callback': {
      id: '/api/ops/auth/callback'
      path: '/api/ops/auth/callback'
      fullPath: '/api/ops/auth/callback'
      preLoaderRoute: typeof ApiOpsAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface KnowledgeRouteRouteChildren {
  KnowledgeIdRoute: typeof KnowledgeIdRoute
  KnowledgeIndexRoute: typeof KnowledgeIndexRoute
}

const KnowledgeRouteRouteChildren: KnowledgeRouteRouteChildren = {
  KnowledgeIdRoute: KnowledgeIdRoute,
  KnowledgeIndexRoute: KnowledgeIndexRoute,
}

const KnowledgeRouteRouteWithChildren = KnowledgeRouteRoute._addFileChildren(
  KnowledgeRouteRouteChildren,
)

interface OpsRouteRouteChildren {
  OpsLoginRoute: typeof OpsLoginRoute
  OpsIndexRoute: typeof OpsIndexRoute
  OpsKnowledgeIndexRoute: typeof OpsKnowledgeIndexRoute
  OpsMatrixIndexRoute: typeof OpsMatrixIndexRoute
}

const OpsRouteRouteChildren: OpsRouteRouteChildren = {
  OpsLoginRoute: OpsLoginRoute,
  OpsIndexRoute: OpsIndexRoute,
  OpsKnowledgeIndexRoute: OpsKnowledgeIndexRoute,
  OpsMatrixIndexRoute: OpsMatrixIndexRoute,
}

const OpsRouteRouteWithChildren = OpsRouteRoute._addFileChildren(
  OpsRouteRouteChildren,
)

interface SkillsRouteRouteChildren {
  SkillsSlugRoute: typeof SkillsSlugRoute
  SkillsIndexRoute: typeof SkillsIndexRoute
}

const SkillsRouteRouteChildren: SkillsRouteRouteChildren = {
  SkillsSlugRoute: SkillsSlugRoute,
  SkillsIndexRoute: SkillsIndexRoute,
}

const SkillsRouteRouteWithChildren = SkillsRouteRoute._addFileChildren(
  SkillsRouteRouteChildren,
)

interface DotwellKnownOauthProtectedResourceRouteChildren {
  DotwellKnownOauthProtectedResourceSplatRoute: typeof DotwellKnownOauthProtectedResourceSplatRoute
}

const DotwellKnownOauthProtectedResourceRouteChildren: DotwellKnownOauthProtectedResourceRouteChildren =
  {
    DotwellKnownOauthProtectedResourceSplatRoute:
      DotwellKnownOauthProtectedResourceSplatRoute,
  }

const DotwellKnownOauthProtectedResourceRouteWithChildren =
  DotwellKnownOauthProtectedResourceRoute._addFileChildren(
    DotwellKnownOauthProtectedResourceRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KnowledgeRouteRoute: KnowledgeRouteRouteWithChildren,
  OpsRouteRoute: OpsRouteRouteWithChildren,
  SkillsRouteRoute: SkillsRouteRouteWithChildren,
  McpRoute: McpRoute,
  QuickStartRoute: QuickStartRoute,
  DotwellKnownOauthAuthorizationServerRoute:
    DotwellKnownOauthAuthorizationServerRoute,
  DotwellKnownOauthProtectedResourceRoute:
    DotwellKnownOauthProtectedResourceRouteWithChildren,
  ApiOpsAuthCallbackRoute: ApiOpsAuthCallbackRoute,
  ApiOpsAuthLoginRoute: ApiOpsAuthLoginRoute,
  ApiOpsAuthLogoutRoute: ApiOpsAuthLogoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
