/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QuickStartRouteImport } from './routes/quick-start'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as OpsRouteRouteImport } from './routes/ops/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SkillsIndexRouteImport } from './routes/skills/index'
import { Route as OpsIndexRouteImport } from './routes/ops/index'
import { Route as KnowledgeIndexRouteImport } from './routes/knowledge/index'
import { Route as SkillsSlugRouteImport } from './routes/skills/$slug'
import { Route as OpsLoginRouteImport } from './routes/ops/login'
import { Route as KnowledgeIdRouteImport } from './routes/knowledge/$id'
import { Route as OpsMatrixIndexRouteImport } from './routes/ops/matrix/index'
import { Route as OpsKnowledgeIndexRouteImport } from './routes/ops/knowledge/index'
import { Route as ApiOpsAuthLogoutRouteImport } from './routes/api/ops/auth/logout'
import { Route as ApiOpsAuthLoginRouteImport } from './routes/api/ops/auth/login'
import { Route as ApiOpsAuthCallbackRouteImport } from './routes/api/ops/auth/callback'

const QuickStartRoute = QuickStartRouteImport.update({
  id: '/quick-start',
  path: '/quick-start',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsRouteRoute = OpsRouteRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsIndexRoute = SkillsIndexRouteImport.update({
  id: '/skills/',
  path: '/skills/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsIndexRoute = OpsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OpsRouteRoute,
} as any)
const KnowledgeIndexRoute = KnowledgeIndexRouteImport.update({
  id: '/knowledge/',
  path: '/knowledge/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsSlugRoute = SkillsSlugRouteImport.update({
  id: '/skills/$slug',
  path: '/skills/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsLoginRoute = OpsLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => OpsRouteRoute,
} as any)
const KnowledgeIdRoute = KnowledgeIdRouteImport.update({
  id: '/knowledge/$id',
  path: '/knowledge/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsMatrixIndexRoute = OpsMatrixIndexRouteImport.update({
  id: '/matrix/',
  path: '/matrix/',
  getParentRoute: () => OpsRouteRoute,
} as any)
const OpsKnowledgeIndexRoute = OpsKnowledgeIndexRouteImport.update({
  id: '/knowledge/',
  path: '/knowledge/',
  getParentRoute: () => OpsRouteRoute,
} as any)
const ApiOpsAuthLogoutRoute = ApiOpsAuthLogoutRouteImport.update({
  id: '/api/ops/auth/logout',
  path: '/api/ops/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpsAuthLoginRoute = ApiOpsAuthLoginRouteImport.update({
  id: '/api/ops/auth/login',
  path: '/api/ops/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpsAuthCallbackRoute = ApiOpsAuthCallbackRouteImport.update({
  id: '/api/ops/auth/callback',
  path: '/api/ops/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ops': typeof OpsRouteRouteWithChildren
  '/mcp': typeof McpRoute
  '/quick-start': typeof QuickStartRoute
  '/knowledge/$id': typeof KnowledgeIdRoute
  '/ops/login': typeof OpsLoginRoute
  '/skills/$slug': typeof SkillsSlugRoute
  '/knowledge/': typeof KnowledgeIndexRoute
  '/ops/': typeof OpsIndexRoute
  '/skills/': typeof SkillsIndexRoute
  '/ops/knowledge/': typeof OpsKnowledgeIndexRoute
  '/ops/matrix/': typeof OpsMatrixIndexRoute
  '/api/ops/auth/callback': typeof ApiOpsAuthCallbackRoute
  '/api/ops/auth/login': typeof ApiOpsAuthLoginRoute
  '/api/ops/auth/logout': typeof ApiOpsAuthLogoutRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/quick-start': typeof QuickStartRoute
  '/knowledge/$id': typeof KnowledgeIdRoute
  '/ops/login': typeof OpsLoginRoute
  '/skills/$slug': typeof SkillsSlugRoute
  '/knowledge': typeof KnowledgeIndexRoute
  '/ops': typeof OpsIndexRoute
  '/skills': typeof SkillsIndexRoute
  '/ops/knowledge': typeof OpsKnowledgeIndexRoute
  '/ops/matrix': typeof OpsMatrixIndexRoute
  '/api/ops/auth/callback': typeof ApiOpsAuthCallbackRoute
  '/api/ops/auth/login': typeof ApiOpsAuthLoginRoute
  '/api/ops/auth/logout': typeof ApiOpsAuthLogoutRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ops': typeof OpsRouteRouteWithChildren
  '/mcp': typeof McpRoute
  '/quick-start': typeof QuickStartRoute
  '/knowledge/$id': typeof KnowledgeIdRoute
  '/ops/login': typeof OpsLoginRoute
  '/skills/$slug': typeof SkillsSlugRoute
  '/knowledge/': typeof KnowledgeIndexRoute
  '/ops/': typeof OpsIndexRoute
  '/skills/': typeof SkillsIndexRoute
  '/ops/knowledge/': typeof OpsKnowledgeIndexRoute
  '/ops/matrix/': typeof OpsMatrixIndexRoute
  '/api/ops/auth/callback': typeof ApiOpsAuthCallbackRoute
  '/api/ops/auth/login': typeof ApiOpsAuthLoginRoute
  '/api/ops/auth/logout': typeof ApiOpsAuthLogoutRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ops'
    | '/mcp'
    | '/quick-start'
    | '/knowledge/$id'
    | '/ops/login'
    | '/skills/$slug'
    | '/knowledge/'
    | '/ops/'
    | '/skills/'
    | '/ops/knowledge/'
    | '/ops/matrix/'
    | '/api/ops/auth/callback'
    | '/api/ops/auth/login'
    | '/api/ops/auth/logout'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mcp'
    | '/quick-start'
    | '/knowledge/$id'
    | '/ops/login'
    | '/skills/$slug'
    | '/knowledge'
    | '/ops'
    | '/skills'
    | '/ops/knowledge'
    | '/ops/matrix'
    | '/api/ops/auth/callback'
    | '/api/ops/auth/login'
    | '/api/ops/auth/logout'
  id:
    | '__root__'
    | '/'
    | '/ops'
    | '/mcp'
    | '/quick-start'
    | '/knowledge/$id'
    | '/ops/login'
    | '/skills/$slug'
    | '/knowledge/'
    | '/ops/'
    | '/skills/'
    | '/ops/knowledge/'
    | '/ops/matrix/'
    | '/api/ops/auth/callback'
    | '/api/ops/auth/login'
    | '/api/ops/auth/logout'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OpsRouteRoute: typeof OpsRouteRouteWithChildren
  McpRoute: typeof McpRoute
  QuickStartRoute: typeof QuickStartRoute
  KnowledgeIdRoute: typeof KnowledgeIdRoute
  SkillsSlugRoute: typeof SkillsSlugRoute
  KnowledgeIndexRoute: typeof KnowledgeIndexRoute
  SkillsIndexRoute: typeof SkillsIndexRoute
  ApiOpsAuthCallbackRoute: typeof ApiOpsAuthCallbackRoute
  ApiOpsAuthLoginRoute: typeof ApiOpsAuthLoginRoute
  ApiOpsAuthLogoutRoute: typeof ApiOpsAuthLogoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/quick-start': {
      id: '/quick-start'
      path: '/quick-start'
      fullPath: '/quick-start'
      preLoaderRoute: typeof QuickStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops': {
      id: '/ops'
      path: '/ops'
      fullPath: '/ops'
      preLoaderRoute: typeof OpsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/': {
      id: '/skills/'
      path: '/skills'
      fullPath: '/skills/'
      preLoaderRoute: typeof SkillsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops/': {
      id: '/ops/'
      path: '/'
      fullPath: '/ops/'
      preLoaderRoute: typeof OpsIndexRouteImport
      parentRoute: typeof OpsRouteRoute
    }
    '/knowledge/': {
      id: '/knowledge/'
      path: '/knowledge'
      fullPath: '/knowledge/'
      preLoaderRoute: typeof KnowledgeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/$slug': {
      id: '/skills/$slug'
      path: '/skills/$slug'
      fullPath: '/skills/$slug'
      preLoaderRoute: typeof SkillsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops/login': {
      id: '/ops/login'
      path: '/login'
      fullPath: '/ops/login'
      preLoaderRoute: typeof OpsLoginRouteImport
      parentRoute: typeof OpsRouteRoute
    }
    '/knowledge/$id': {
      id: '/knowledge/$id'
      path: '/knowledge/$id'
      fullPath: '/knowledge/$id'
      preLoaderRoute: typeof KnowledgeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops/matrix/': {
      id: '/ops/matrix/'
      path: '/matrix'
      fullPath: '/ops/matrix/'
      preLoaderRoute: typeof OpsMatrixIndexRouteImport
      parentRoute: typeof OpsRouteRoute
    }
    '/ops/knowledge/': {
      id: '/ops/knowledge/'
      path: '/knowledge'
      fullPath: '/ops/knowledge/'
      preLoaderRoute: typeof OpsKnowledgeIndexRouteImport
      parentRoute: typeof OpsRouteRoute
    }
    '/api/ops/auth/logout': {
      id: '/api/ops/auth/logout'
      path: '/api/ops/auth/logout'
      fullPath: '/api/ops/auth/logout'
      preLoaderRoute: typeof ApiOpsAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ops/auth/login': {
      id: '/api/ops/auth/login'
      path: '/api/ops/auth/login'
      fullPath: '/api/ops/auth/login'
      preLoaderRoute: typeof ApiOpsAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ops/auth/callback': {
      id: '/api/ops/auth/callback'
      path: '/api/ops/auth/callback'
      fullPath: '/api/ops/auth/callback'
      preLoaderRoute: typeof ApiOpsAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface OpsRouteRouteChildren {
  OpsLoginRoute: typeof OpsLoginRoute
  OpsIndexRoute: typeof OpsIndexRoute
  OpsKnowledgeIndexRoute: typeof OpsKnowledgeIndexRoute
  OpsMatrixIndexRoute: typeof OpsMatrixIndexRoute
}

const OpsRouteRouteChildren: OpsRouteRouteChildren = {
  OpsLoginRoute: OpsLoginRoute,
  OpsIndexRoute: OpsIndexRoute,
  OpsKnowledgeIndexRoute: OpsKnowledgeIndexRoute,
  OpsMatrixIndexRoute: OpsMatrixIndexRoute,
}

const OpsRouteRouteWithChildren = OpsRouteRoute._addFileChildren(
  OpsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OpsRouteRoute: OpsRouteRouteWithChildren,
  McpRoute: McpRoute,
  QuickStartRoute: QuickStartRoute,
  KnowledgeIdRoute: KnowledgeIdRoute,
  SkillsSlugRoute: SkillsSlugRoute,
  KnowledgeIndexRoute: KnowledgeIndexRoute,
  SkillsIndexRoute: SkillsIndexRoute,
  ApiOpsAuthCallbackRoute: ApiOpsAuthCallbackRoute,
  ApiOpsAuthLoginRoute: ApiOpsAuthLoginRoute,
  ApiOpsAuthLogoutRoute: ApiOpsAuthLogoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
